
{{ config(
    materialized='table',
    transient=false,
    alias='CUSTOMER_ORACLE_BILL_TO'
) }}

SELECT DISTINCT
                SAHCAB.ACCOUNT_NUMBER AS CUSTOMER_ACCOUNT_NUMBER ,
                SAHPB.PARTY_NAME AS PARTY_NAME,
                SAHCAB.ATTRIBUTE2 AS INDUSTRY_DETAIL,
                FVITB.INTERCOMPANY_TYPE AS INTERCOMPANY_TYPE,
                SRT.ORA_SALESREP_SALESREP_NUMBER AS SALES_AGENT_CODE,------------
                SACAB_FILTERED.CLASS_CODE AS EIA_CUSTOMER_TYPE,
                FCGB.GROUP_CODE AS CUSTOMER_GROUP_CODE,
                FGNB.GROUP_NAME AS CUSTOMER_GROUP_NAME,
                FVITB.PERIMETRE_LS_CONSO AS PERIMETRE_LS_CONSO,
                DECODE(FCGB.GROUP_CODE, NULL, SAHPB.PARTY_NAME, FGNB.GROUP_NAME) AS PARENT_COMPANY,
                SHCSUABTTB.ORG_ID AS ORG_ID,
                SHCSUABTTB.SITE_USE_ID AS SITE_USE_ID,
                SAHAOUB.NAME AS OU_NAME,
                'ORACLE' AS SOURCE,
                SHCSUABTTB.STATUS AS STATUS,
                SAHPB.TAX_REFERENCE AS TAX_REFERENCE,
                SHCSUABTTB.CUST_ACCT_SITE_ID AS CUST_ACCT_SITE_ID,
                SHCSUABTTB.FOB_POINT AS FOB_POINT,
                SHCSUABTTB.FREIGHT_TERM AS FREIGHT_TERM,
                SHCSUABTTB.ATTRIBUTE2 AS METAL_SUPPLEMENT,
                SHCSUABTTB.SITE_USE_CODE AS SITE_USE_CODE,
                SHCSUABTTB.BILL_TO_SITE_USE_ID AS BILL_TO_SITE_USE_ID,
                SHCSUABTTB.GL_ID_REC AS GL_ID_REC,
                SHCSUABTTB.GL_ID_REV AS GL_ID_REV,
                SHCSUABTTB.LAST_UPDATE_DATE AS LAST_UPDATE_DATE,
             /*   SAGCCKB.SEGMENT4 AS ACCOUNT_GL_CODE,   -- remplacement par le revenue account le 25/02/25 car mieux renseign� que le receivable account
                SAGCCKB.SEGMENT1 AS BU_GL_CODE,
                SAGCCKB.SEGMENT3 AS DPT_GL_CODE,
                SAGCCKB.SEGMENT6 AS INTERCOMPANY_GL_CODE,
                SAGCCKB.SEGMENT5 AS PRODUCT_GROUP_GL_CODE, */ 
                SAGCCKBV.SEGMENT4 AS ACCOUNT_GL_CODE,
                SAGCCKBV.SEGMENT1 AS BU_GL_CODE,
                SAGCCKBV.SEGMENT3 AS DPT_GL_CODE,
                SAGCCKBV.SEGMENT6 AS INTERCOMPANY_GL_CODE,
                SAGCCKBV.SEGMENT5 AS PRODUCT_GROUP_GL_CODE,
                SAGCCKB.CONCATENATED_SEGMENTS AS RECEIVABLE_ACCOUNT,
             --   SAGCCKB.CONCATENATED_SEGMENTS AS REVENUE_ACCOUNT,  
                SAGCCKBV.CONCATENATED_SEGMENTS AS REVENUE_ACCOUNT,
             --   SAGCCKB.SEGMENT2 AS SITE_GL_CODE,  -- remplacement par le revenue account le 25/02/25 car mieux renseign� que le receivable account
                SAGCCKBV.SEGMENT2 AS LOCATION_GL_CODE  ,   -- renommage le 25/02/25 avant : SITE_GL_CODE
                SAHASAB.PARTY_SITE_ID AS PARTY_SITE_ID,
                SAHASAB.CUST_ACCOUNT_ID AS CUST_ACCOUNT_ID,
                SAHPSB.ADDRESSEE AS ADDRESSEE,
                SAHPSB.LOCATION_ID AS LOCATION_ID,
                SAHPSB.PARTY_ID AS PARTY_ID,
                SAHPSB.PARTY_SITE_NUMBER AS PARTY_SITE_NUMBER,
                SAHPB.SIC_CODE AS SIC_CODE,
                ffvb.DESCRIPTION_ffv_tl AS INDUSTRY_DETAIL_DESCRIPTION,
                SAHCAB.CREATION_DATE AS CREATION_DATE,
                SAHCAB.CUSTOMER_TYPE AS CUSTOMER_TYPE,
                SAHCAB.ATTRIBUTE1 AS INDUSTRY_VERTICAL,
                ffv.DESCRIPTION_ffv_tl AS INDUSTRY_VERTICAL_DESCRIPTION,
                SAHCPB.COLLECTOR_ID AS COLLECTOR_ID,
                --SAHCPB.CREDIT_CHECKING AS CREDIT_CHECKING,
                --SAHCPB.CREDIT_HOLD AS CREDIT_HOLD,
                COALESCE(NULLIF(TRIM(SAHCPB.CREDIT_CHECKING), ''), 'N') AS CREDIT_CHECKING, --"N" par d�faut sur si vide
                COALESCE(NULLIF(TRIM(SAHCPB.CREDIT_HOLD), ''), 'N') AS CREDIT_HOLD, --"N" par d�faut sur si vide
                SRT.ORA_SALESREP_SALESREP_IDA AS SALESREP_ID,
                SAHLB.COUNTRY AS COUNTRY_CODE,
                SAHLB.CITY AS TOWN,
                SAHLB.POSTAL_CODE AS POSTAL_CODE,
                SAHLB.PROVINCE AS PROVINCE,
                SAHLB.STATE AS STATE,
                SAHLB.ADDRESS1 AS ADDRESS1,
                SAHLB.ADDRESS2 AS ADDRESS2,
                SAHLB.ADDRESS3 AS ADDRESS3,
                SAHLB.ADDRESS4 AS ADDRESS4,
                SAACB.NAME AS COLLECTOR_NAME,
                SRT.AS400_AGENT_LIBELLE AS SALESREP_NAME,--------------
                SRT.AS400_SUCCURSALE_LIBELLE AS SALESREP_BRANCH_NAME,--------------
                --SRT.WSUSUC AS SALESREP_BRANCH,-------------------- N'EXISTE PAS
                SRT.AS400_SUCCURSALE AS SALESREP_BRANCH,
                SRT.AS400_MARCHE AS SALESREP_MARKET,-----------
                SRT.AS400_REGION_LIBELLE AS SALESREP_AREA_NAME,----------
               -- SRT.WRGREG AS SALESREP_AREA,-------- N'EXISTE PAS
                SRT.AS400_REGION AS SALESREP_AREA,
                SRT.AS400_MARCHE_LIBELLE AS SALESREP_MARKET_NAME,------------
                SAHCCDB.CLASS_CODE_MEANING AS LIBELLE_EIA_CUSTOMER_TYPE,
                SAHLAB.LOCATION_CODE AS INTERNAL_LOCATION,
                SAMPB.ORGANIZATION_ID AS INTERNAL_ORGANIZATION,
                SARTB.NAME AS PAYMENT_TERM,
                SARTB.DESCRIPTION AS PAYMENT_TERM_DESCRIPTION,
                FCZB.COUNTRY_NAME_EN,
                FCZB.ZONE_EPG,
                FCZB.ZONE_MDE,
                FCZB.ZONE_1_CIMD,
                FCZB.ZONE_2_CIMD,
                FCZB.ZONE_3_CIMD,
                sagcckb.CHART_OF_ACCOUNTS_ID CHART_OF_ACCOUNTS_ID_REC,
                sagcckbv.CHART_OF_ACCOUNTS_ID CHART_OF_ACCOUNTS_ID_REV,
                SHCSUABTTB.ship_via,
                SHCSUABTTB.attribute4 DFF_FREIGHT, 
                SHCSUABTTB.attribute8 DFF_FREIGHT_CHARGE,
                SRT. ORA_RESOURCE_RESOURCE_NAME EIA_SALESPERSON_NAME,-----------
                FCGB.CUSTOMER_ACTIVITY,
                SAHASAB.orig_system_reference,
                SHCSUABTTB.PRIMARY_FLAG,
                SAHCAB.STATUS AS STATUS_ACCOUNT,
                fu2.user_name created_by_account,
                SAHCAB.CREATION_DATE CREATION_DATE_ACCOUNT,
                fu1.user_name LAST_UPDATED_BY_account,
                SAHCAB.LAST_UPDATE_DATE LAST_UPDATE_DATE_account,
                fu4.user_name CREATED_BY,
                fu3.user_name LAST_UPDATE_BY,
                fczb.currency country_currency
FROM DEV.LH2_SILVER_DEV.DEV.LH2_SILVER_DEV.STEPH_HZ_CUST_SITE_USES_ALL_BILL_TO_TEMP SHCSUABTTB
JOIN DEV.LH2_BRONZE_DEV.STEPH_APPS_HR_ALL_ORGANIZATION_UNITS SAHAOUB
  ON SHCSUABTTB.ORG_ID = SAHAOUB.ORGANIZATION_ID

LEFT JOIN DEV.LH2_BRONZE_DEV.STEPH_APPS_GL_CODE_COMBINATIONS_KFV SAGCCKB
  ON SHCSUABTTB.GL_ID_REC = SAGCCKB.CODE_COMBINATION_ID
LEFT JOIN DEV.LH2_BRONZE_DEV.STEPH_APPS_GL_CODE_COMBINATIONS_KFV SAGCCKBV
  ON SHCSUABTTB.GL_ID_REV = SAGCCKBV.CODE_COMBINATION_ID

LEFT JOIN DEV.LH2_BRONZE_DEV.FILE_INTERCO_SEGMENT6 FVITB
  ON SAGCCKBV.SEGMENT6 = FVITB.INTERCOMPANY_GL_CODE

LEFT JOIN DEV.LH2_BRONZE_DEV.STEPH_APPS_HZ_CUST_ACCT_SITES_ALL SAHASAB
  ON SHCSUABTTB.CUST_ACCT_SITE_ID = SAHASAB.CUST_ACCT_SITE_ID
LEFT JOIN DEV.LH2_BRONZE_DEV.STEPH_APPS_HZ_PARTY_SITES SAHPSB
  ON SAHASAB.PARTY_SITE_ID = SAHPSB.PARTY_SITE_ID

LEFT JOIN (
  SELECT a.*
  FROM DEV.LH2_SILVER_DEV.DEV.LH2_BRONZE_DEV.STEPH_APPS_HZ_PARTIES a
  JOIN ( SELECT PARTY_ID
          FROM DEV.LH2_SILVER_DEV.DEV.LH2_BRONZE_DEV.STEPH_APPS_HZ_PARTIES
         GROUP BY PARTY_ID ) b
    ON a.PARTY_ID = b.PARTY_ID
) SAHPB
  ON SAHPSB.PARTY_ID = SAHPB.PARTY_ID

LEFT JOIN DEV.LH2_BRONZE_DEV.STEPH_APPS_HZ_CUST_ACCOUNTS SAHCAB
  ON SAHASAB.CUST_ACCOUNT_ID = SAHCAB.CUST_ACCOUNT_ID

LEFT JOIN (
  SELECT DESCRIPTION_ffv_tl, FLEX_VALUE_ffv_values
  FROM DEV.LH2_SILVER_DEV.DEV.LH2_SILVER_DEV.FND_FLEX_VALUES_US
  WHERE FLEX_VALUE_SET_NAME_ffv_set = 'XXAR_INDUSTRY_VERTICAL_EIA'
    AND PARENT_FLEX_VALUE_LOW_FFV_VALUES IS NULL
) ffv
  ON SAHCAB.ATTRIBUTE1 = ffv.FLEX_VALUE_ffv_values

LEFT JOIN (
  SELECT DESCRIPTION_ffv_tl, FLEX_VALUE_ffv_values, PARENT_FLEX_VALUE_LOW_FFV_VALUES
  FROM DEV.LH2_SILVER_DEV.DEV.LH2_SILVER_DEV.FND_FLEX_VALUES_US
  WHERE FLEX_VALUE_SET_NAME_ffv_set = 'XXAR_INDUSTRY_DETAILS_EIA'
) ffvb
  ON SAHCAB.ATTRIBUTE2 = ffvb.FLEX_VALUE_ffv_values
 AND SAHCAB.ATTRIBUTE1 = ffvb.PARENT_FLEX_VALUE_LOW_FFV_VALUES

-- ...
JOIN DEV.LH2_SILVER_DEV.COUNTRY_ZONE FCZB
  ON SAHLB.COUNTRY = FCZB.COUNTRY_CODE

LEFT JOIN DEV.LH2_BRONZE_DEV.STEPH_APPS_FND_USER fu1
  ON SAHCAB.LAST_UPDATED_BY = fu1.USER_ID
LEFT JOIN DEV.LH2_BRONZE_DEV.STEPH_APPS_FND_USER fu2
  ON SAHCAB.CREATED_BY = fu2.USER_ID
LEFT JOIN DEV.LH2_BRONZE_DEV.STEPH_APPS_FND_USER fu3
  ON SHCSUABTTB.LAST_UPDATED_BY = fu3.USER_ID
LEFT JOIN DEV.LH2_BRONZE_DEV.STEPH_APPS_FND_USER fu4
  ON SHCSUABTTB.CREATED_BY = fu4.USER_ID

